### ISSUE TITLE
How to use es5

### ISSUE THREAD

**Issue by panagorn** [sebs/es6-fuzz#63]
Hello thank you for the lib. I want to use es5 i put the following code
var es6ify = require('./es6-fuzz-latest.js');

How can i do var logic = new Logic()

**Comment by sebs** [comment]
I will check this out and provide docs if it is ok. Didnt work on this for a time, so I have to get back into it. Happy it helps though. If you have more wishes and maybe feature ideas: add them. I am happy to listen

**Comment by sebs** [comment]
you can use the file from the [dist folder](https://github.com/sebs/es6-fuzz/blob/master/dist/es6-fuzz-2.5.10.js) in you project. simply copy it into your node project
